name: aoc
description: Advent of Code 2023 solutions
version: 1.0.0
homepage: https://github.com/woog-life/api

environment:
  sdk: ^3.0.0

dependencies:
  get_it: ^7.0.0
  injectable: ^2.0.0
  logger: ^2.0.0
  meta: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_version: ^2.0.0
  injectable_generator: ^2.0.0
  lints: ^3.0.0
  test: ^1.0.0
