name: aoc
description: Advent of Code 2023 solutions
version: 1.0.0
homepage: https://github.com/woog-life/api

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  async: ^2.11.0
  collection: ^1.18.0
  logger: ^2.0.0
  meta: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.0.0
