name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }


jobs:
  validate-renovate-config:
    name: Validate Renovate configuration
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - name: Get dependencies
        run: dart pub get
      - name: Run tests
        run: dart test

  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - name: Check bin formatting
        run: dart format bin --set-exit-if-changed
      - name: Check lib formatting
        run: dart format lib --set-exit-if-changed
      - name: Check test formatting
        run: dart format test --set-exit-if-changed

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - name: Get dependencies
        run: dart pub get
      - name: Run Analysis
        run: dart analyze --fatal-infos

  build:
    name: Build binary
    if: github.ref_name == github.event.repository.default_branch
    needs:
      - validate-renovate-config
      - test
      - check-format
      - lint
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          # renovate: datasource=docker depName=dart
          sdk: 3.2.4
      - run: |
          dart pub get
          mkdir output
      - run: |
          if [ "${{ matrix.runner }}" == "ubuntu-latest" ]
          then
            os="linux"
          else
            os="macos"
          fi
          filename="output/advent-${os}"
          dart compile exe bin/main.dart -o "$filename"
          chmod +x "$filename"
        if: matrix.runner != 'windows-latest'
      - run: dart compile exe bin/main.dart -o "output/advent-win.exe"
        if: matrix.runner == 'windows-latest'
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: output/*
