name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }


jobs:
  validate-renovate-config:
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - name: Get dependencies
        run: dart pub get
      - name: Run tests
        run: dart test

  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - name: Check bin formatting
        run: dart format bin --set-exit-if-changed
      - name: Check lib formatting
        run: dart format lib --set-exit-if-changed
      - name: Check test formatting
        run: dart format test --set-exit-if-changed

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - name: Get dependencies
        run: dart pub get
      - name: Run Analysis
        run: dart analyze --fatal-infos

  build:
    if: github.ref_name == github.event.repository.default_branch
    needs:
      - validate-renovate-config
      - test
      - check-format
      - lint
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          # renovate: datasource=docker depName=dart
          sdk: 3.2.1
      - run: |
          dart compile exe bin/main.dart
